config/routes.rb
RssProject::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root :to => "categories#index"

  resources :bookmarks

  resources :categories

  resources :subscriptions

  resources :articles

  resources :feeds

  root :to => 'categories#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RSS APP
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=The+Girl+Next+Door|Offside|Atomic+Age|Londrina+Outline|Hind|Over+the+Rainbow", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    .header
      %h1 
        Feed.
        %span{class: "me", data: {text: "me"}}
          me
      %h2 RSS feed your brain
      %br
      %p Menu
      %i#show_hide.fa.fa-circle-o-notch.btn


    #user_nav.user-nav
      #menu_items
        - if user_signed_in?
          %h3= current_user.name
          = image_tag current_user.image.thumb.url
          %br
          = link_to 'Edit Profile', edit_user_registration_path
          = link_to 'Logout',  destroy_user_session_path, method: :delete
          %br
          %h3=link_to 'Feeds', feeds_path
          %i.fa.fa-graduation-cap
          %h3=link_to 'Categories', categories_path
          %i.fa.fa-newspaper-o
          %h3#bkmks.a Bookmarks
          %i.fa.fa-book
          %h3#subs.a Subscriptions
          .subs
            =raw subscription_menu_items(@subscriptions_title)
            =link_to 'All', subscriptions_path

          .bkmks
            =raw bookmark_menu_items(@bookmarks_title)
            %br
            =link_to 'All', bookmarks_path

        - else
          = link_to 'Sign up', new_user_registration_path
          \|
          = link_to 'Login', new_user_session_path

    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}"
    
    .container
      #main_page_content  
      = yield